version: '3'

services:
  node:
    build: ./courier-capacity-manager
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://courier-database:temp_passwd@mongo
  mongo:
    image: mongo:4.0
    volumes:
      - "./courier-database/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=courier-database
      - MONGO_INITDB_ROOT_PASSWORD=temp_passwd
